#ifndef OREZ_CLUSTERING_GLOBAL_H
#define OREZ_CLUSTERING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OREZ_CLUSTERING_LIBRARY)
#  define OREZ_CLUSTERINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OREZ_CLUSTERINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OREZ_CLUSTERING_GLOBAL_H
