#ifndef OREZ_RECONSTRUCT_GLOBAL_H
#define OREZ_RECONSTRUCT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OREZ_RECONSTRUCT_LIBRARY)
#  define OREZ_RECONSTRUCTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OREZ_RECONSTRUCTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OREZ_RECONSTRUCT_GLOBAL_H
